import React from 'react';
import Head from 'next/head';
import styles from './index.module.scss';
import pageConfig from '../magnolia.config';
import { EditablePage } from '@magnolia/react-editor';
import { useEffect, useState } from 'react';
import AppContext from '../utils/hooks/context';
import {
  buildMagnoliaDataPath,
  getAcceptLang,
  getCleanCurrentPathParts,
  getMagnoliaData,
  useMagnoliaData,
} from '../utils/magnolia-data-requests';
import {
  GetStaticProps,
  GetStaticPropsContext,
  GetStaticPropsResult,
} from 'next';
import normalizeSluck from '../utils/normalize-sluck';

interface PageProps {
  host: string;
  secret: string;
  authorPathPart: string;
  pageJson: unknown;
  templateDefinitions: unknown;
  preview: boolean;
  apiBase: string;
  pageJsonPath: string;
  pageTemplateDefinitionsPath: string | undefined;
  currentPathname: string;
  languages: string[];
  acceptLanguages: { [key: string]: string };
  registerPreview: boolean;
  fetchInterval: number;
}

export default function Page(props: PageProps) {
  const {
    host,
    currentPathname,
    preview,
    secret,
    authorPathPart,
    languages,
    acceptLanguages,
    registerPreview,
    fetchInterval,
  } = props;
  const environmentPathName =
    typeof window !== 'undefined' && window.location
      ? window.location.pathname
      : currentPathname;
  const { pathname, language } = getCleanCurrentPathParts(
    environmentPathName,
    authorPathPart,
    languages
  );
  const [registerPreviewState, setRegisterPreviewState] =
    useState(registerPreview);
  const [state, setState] = useState({
    ...props,
    language,
    pageConfig,
  });

  const { data, error } = useMagnoliaData<PageProps>({
    host,
    language: state.language,
    acceptLanguages,
    registerPreview: registerPreviewState,
    preview: state.preview,
    secret,
    pathname,
    props,
    fetchInterval,
  });

  useEffect(() => {
    setState({
      ...data,
      pageConfig,
    });

    if (registerPreviewState && data.preview) {
      setRegisterPreviewState(false);
    }
  }, [data]);

  if (error) {
    console.log('Error for path', pathname, preview, `${host}/api/${pathname}`);
    console.log(error);
    return <pre>error {JSON.stringify(error, null, 4)}</pre>;
  }

  return (
    <AppContext.Provider value={[state, setState]}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {state.pageJson && (
          <EditablePage
            content={state.pageJson}
            config={state.pageConfig}
            templateDefinitions={state.templateDefinitions}
          />
        )}
      </div>
    </AppContext.Provider>
  );
}
export const getStaticProps: GetStaticProps<PageProps> = async ({
  preview,
  params,
}: GetStaticPropsContext): Promise<GetStaticPropsResult<PageProps>> => {
  const {
    NODE_ENV,
    NEXTJS_HOST,
    NEXTJS_PUBLIC_FETCH_INTERVAL,
    MGNL_PATH_AUTHOR,
    MGNL_LANGUAGES,
    MGNL_PREVIEW_EXPORT,
    MGNL_PREVIEW_SECRET,
  } = process.env;

  preview = Boolean(preview);
  // in case it is a build as a preview export this will evaluate to true
  const registerPreview = Boolean(!preview && MGNL_PREVIEW_EXPORT);
  // available languages as object to be used to set language headers
  const acceptLanguages = JSON.parse(MGNL_LANGUAGES as string);
  // helper object containing short lang parameters
  // used for non-localized shortend language variant param, e.g. en for en-GB
  const languages = Object.keys(acceptLanguages);
  const slug = normalizeSluck(params);
  // build the path to request Magnolia pageJSON endpoint
  const {
    apiBase,
    currentPathname,
    language,
    pageJsonPath,
    pageTemplateDefinitionsPath = '',
  } = buildMagnoliaDataPath(slug, registerPreview, languages);

  let pageJson;
  let templateDefinitions;

  try {
    const response = await getMagnoliaData({
      apiBase,
      pageJsonPath,
      pageTemplateDefinitionsPath,
      acceptLanguage: getAcceptLang(language, acceptLanguages),
      acceptLanguages,
    });
    pageJson = response && response.pageJson ? response.pageJson : null;
    templateDefinitions =
      response && response.templateDefinitions
        ? response.templateDefinitions
        : null;
  } catch (e) {
    console.log('getMagnoliaData error', e);
    pageJson = null;
    templateDefinitions = null;
  }

  const fetchInterval = parseInt(NEXTJS_PUBLIC_FETCH_INTERVAL || '0', 10);

  return {
    props: {
      host: String(NEXTJS_HOST),
      authorPathPart: String(MGNL_PATH_AUTHOR),
      secret: String(MGNL_PREVIEW_SECRET),
      pageJson,
      templateDefinitions,
      preview,
      apiBase,
      pageJsonPath,
      pageTemplateDefinitionsPath,
      currentPathname,
      languages,
      acceptLanguages,
      registerPreview,
      fetchInterval: preview || registerPreview ? 0 : fetchInterval,
    },
    revalidate: fetchInterval / 1000,
  };
};
