import Head from 'next/head'
import styles from './index.module.scss'
import pageConfig from '../magnolia.config';
import { EditablePage } from '@magnolia/react-editor';
import { useState } from 'react';
import AppContext from '../utils/hooks/context';

export default function Index(props: any) {
    const { pageJson, templateDefinitions, preview, apiBase } = props;
    const [state, setState] = useState({
        pageJson,
        pageConfig,
        templateDefinitions,
        preview,
        apiBase
    });

    console.log(JSON.stringify(props, null, 4));

    return (
        <AppContext.Provider value={[state, setState]}>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                {state.preview && pageJson && <EditablePage content={pageJson} config={pageConfig} templateDefinitions={templateDefinitions} />}
            </div>
        </AppContext.Provider>
    )
}

export async function getStaticProps({ preview = process.env.MGNL_PREVIEW }: any) {
    const { MGNL_HOST, MGNL_PATH_AUTHOR, MGNL_PREVIEW, MGNL_API_TEMPLATES, MGNL_API_PAGES } = process.env;
    const apiBase = `${MGNL_HOST}${MGNL_PREVIEW ? MGNL_PATH_AUTHOR : ''}`;
    const pageJsonEndpoint = `${apiBase}${MGNL_API_PAGES}/Home`;

    let response = await fetch(pageJsonEndpoint);
    const pageJson = await response.json();
    response = await fetch(`${apiBase}${MGNL_API_TEMPLATES}` + '/' + pageJson['mgnl:template']);
    const templateDefinitions = await response.json();

    return {
        props: { pageJson, templateDefinitions, preview, apiBase },
        revalidate: 10
    }
}